variable "name" {}
variable "clusterId" {}
variable "serviceLaunchType" {}
variable "taskDenitionArn" {} 
variable "taskDesiredCount" {}  
variable "DeploymentMaximumCount" {}
variable "deploymentHealthyPercent" {}
variable "subnets" {} 
variable "sgGroupName" {}
variable "vpc" {}