AWSTemplateFormatVersion: "2010-09-09"
Description: "This is to create bucket"
Parameters:
  {{ bucketName }}:
    Description: db user
    Type: String

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties: 
      BucketName: 
        !Ref {{ bucketName }}
      Tags:
        - Key: Name
          Value: Deshraj
